name: CI

on:
  push:
    branches: ["main"]

# TODO: add steps
jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v4
