name: CI

on:
  push:
    branches: ["main"]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE
          xcodebuild \
              -project ./AlarmClock.xcodeproj \
              -scheme AlarmClock \
              -sdk iphoneos \
              -configuration Release \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO

      - name: Construct IPA
        run: |
          cd ~/Library/Developer/Xcode/DerivedData/AlarmClock-*/Build/Products/Release-iphoneos
          mkdir ./Payload
          mv ./AlarmClock.app ./Payload/AlarmClock.app
          zip -r ./AlarmClock.ipa ./Payload
          mv ./AlarmClock.ipa $GITHUB_WORKSPACE/
          cd $GITHUB_WORKSPACE
          ls -al

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AlarmClock.ipa
          path: $GITHUB_WORKSPACE/AlarmClock.ipa
          retention-days: 90
          if-no-files-found: error
