name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        working-directory: ${{ github.workspace }}
        run: |
          xcodebuild \
              -project ./AlarmClock.xcodeproj \
              -scheme AlarmClock \
              -sdk iphoneos \
              -configuration Release \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        working-directory: ${{ github.workspace }}
        run: swiftlint --strict

      - name: Construct IPA
        run: |
          cd ~/Library/Developer/Xcode/DerivedData/AlarmClock-*/Build/Products/Release-iphoneos
          mkdir ./Payload
          mv ./AlarmClock.app ./Payload/
          ditto -c -k --sequesterRsrc --keepParent ./Payload AlarmClock.zip
          mv ./AlarmClock.zip ${{ github.workspace }}/AlarmClock.ipa

      - name: Wait for IPA construction
        run: sleep 5

      - name: Set variables to output
        id: variables
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: AlarmClock-${{ steps.variables.outputs.sha_short }}.ipa
          path: ${{ github.workspace }}/AlarmClock.ipa
          retention-days: 3
          if-no-files-found: error

      - name: Rename IPA
        if: github.ref_type == 'tag'
        working-directory: ${{ github.workspace }}
        run: |
          mv ./AlarmClock.ipa ./AlarmClock-${{ github.ref_name }}.ipa

      - name: Release IPA
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ${{ github.workspace }}/AlarmClock-${{ github.ref_name }}.ipa
