name: CI

on:
  push:
    branches: ["main"]

# TODO: add SwiftLint
jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        working-directory: ${{ github.workspace }}
        run: |
          xcodebuild \
              -project ./AlarmClock.xcodeproj \
              -scheme AlarmClock \
              -sdk iphoneos \
              -configuration Release \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO

      - name: Construct IPA
        run: |
          cd ~/Library/Developer/Xcode/DerivedData/AlarmClock-*/Build/Products/Release-iphoneos
          mkdir ./Payload
          mv ./AlarmClock.app ./Payload/
          ditto -c -k --sequesterRsrc --keepParent ./Payload AlarmClock.zip
          mv ./AlarmClock.zip ${{ github.workspace }}/AlarmClock.ipa

      - name: Wait for IPA construction
        run: sleep 5

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AlarmClock.ipa
          path: ${{ github.workspace }}/AlarmClock.ipa
          retention-days: 90
          if-no-files-found: error
